-- ════════════════════════════════════════════════════════════════════
-- Baseline 20 — CONSTRAINTS (PK/UNIQUE/CHECK then FK) + INDEXES
-- Reconstructed from live fmrsfjxwswzhvicylaph 2026-06-29 (pg_get_constraintdef
-- / pg_get_indexdef — authoritative). Apply AFTER 10_tables.sql.
-- NOTE: several FKs reference auth.users(id); apply on a Supabase project where
-- the auth schema exists. Key facts: class_children.teacher_id → auth.users,
-- sessions.teacher_id → teachers(id), teachers.id → auth.users(id).
-- ════════════════════════════════════════════════════════════════════

-- ── Primary keys, unique & check constraints ─────────────────────────
ALTER TABLE public.admin_alerts ADD CONSTRAINT admin_alerts_pkey PRIMARY KEY (id);
ALTER TABLE public.admin_alerts ADD CONSTRAINT admin_alerts_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text])));
ALTER TABLE public.analytics_events ADD CONSTRAINT analytics_events_pkey PRIMARY KEY (id);
ALTER TABLE public.billing_events ADD CONSTRAINT billing_events_pkey PRIMARY KEY (id);
ALTER TABLE public.billing_events ADD CONSTRAINT billing_events_stripe_event_id_key UNIQUE (stripe_event_id);
ALTER TABLE public.broadcast_log ADD CONSTRAINT broadcast_log_pkey PRIMARY KEY (campaign, email);
ALTER TABLE public.child_activity_summary ADD CONSTRAINT child_activity_summary_child_profile_id_activity_key_key UNIQUE (child_profile_id, activity_key);
ALTER TABLE public.child_activity_summary ADD CONSTRAINT child_activity_summary_pkey PRIMARY KEY (id);
ALTER TABLE public.child_learning_state ADD CONSTRAINT child_learning_state_pkey PRIMARY KEY (child_profile_id);
ALTER TABLE public.child_profiles ADD CONSTRAINT child_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.class_children ADD CONSTRAINT class_children_age_band_check CHECK ((age_band = ANY (ARRAY['3-4'::text, '5-7'::text])));
ALTER TABLE public.class_children ADD CONSTRAINT class_children_first_name_check CHECK (((length(TRIM(BOTH FROM first_name)) >= 1) AND (length(TRIM(BOTH FROM first_name)) <= 40)));
ALTER TABLE public.class_children ADD CONSTRAINT class_children_nickname_check CHECK (((nickname IS NULL) OR (length(TRIM(BOTH FROM nickname)) <= 40)));
ALTER TABLE public.class_children ADD CONSTRAINT class_children_notes_check CHECK (((notes IS NULL) OR (length(notes) <= 2000)));
ALTER TABLE public.class_children ADD CONSTRAINT class_children_pkey PRIMARY KEY (id);
ALTER TABLE public.classroom_default_activities ADD CONSTRAINT classroom_default_activities_pkey PRIMARY KEY (id);
ALTER TABLE public.classroom_default_activities ADD CONSTRAINT classroom_default_activities_session_id_key UNIQUE (session_id);
ALTER TABLE public.client_errors ADD CONSTRAINT client_errors_pkey PRIMARY KEY (id);
ALTER TABLE public.consent_records ADD CONSTRAINT consent_records_pkey PRIMARY KEY (id);
ALTER TABLE public.data_deletion_requests ADD CONSTRAINT data_deletion_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.form_submissions ADD CONSTRAINT form_submissions_pkey PRIMARY KEY (id);
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_affect_check CHECK ((affect_tags <@ ARRAY['confident'::text, 'calm'::text, 'hesitant'::text, 'frustrated'::text]));
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_fact_pkey PRIMARY KEY (id);
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_focus_check CHECK ((focus_tags <@ ARRAY['focused'::text, 'distracted'::text, 'disengaged'::text]));
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_independence_check CHECK ((independence_tags <@ ARRAY['independent'::text, 'supported'::text, 'required_intervention'::text]));
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_notable_check CHECK ((notable_tags <@ ARRAY['new_behaviour_good'::text, 'new_behaviour_concern'::text, 'help_needed'::text, 'breakthrough'::text, 'avoided_activity'::text]));
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_note_length CHECK (((note IS NULL) OR (char_length(note) <= 200)));
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_observer_role_check CHECK ((observer_role = ANY (ARRAY['teacher'::text, 'parent'::text, 'researcher'::text])));
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_social_check CHECK ((social_tags <@ ARRAY['alone'::text, 'collaborated'::text, 'disrupted_by_peer'::text]));
ALTER TABLE public.item_difficulty ADD CONSTRAINT item_difficulty_pkey PRIMARY KEY (item_key, game_mode);
ALTER TABLE public.join_audit_log ADD CONSTRAINT join_audit_log_event_check CHECK ((event = ANY (ARRAY['join_attempt'::text, 'join_success'::text, 'join_failure'::text, 'network_match'::text, 'network_mismatch'::text])));
ALTER TABLE public.join_audit_log ADD CONSTRAINT join_audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.join_rate_limits ADD CONSTRAINT join_rate_limits_pkey PRIMARY KEY (ip_hash);
ALTER TABLE public.learning_attempts ADD CONSTRAINT learning_attempts_credibility_score_range CHECK (((credibility_score IS NULL) OR ((credibility_score >= (0)::numeric) AND (credibility_score <= (1)::numeric))));
ALTER TABLE public.learning_attempts ADD CONSTRAINT learning_attempts_credibility_tier_check CHECK (((credibility_tier IS NULL) OR (credibility_tier = ANY (ARRAY['A'::text, 'B'::text, 'C'::text]))));
ALTER TABLE public.learning_attempts ADD CONSTRAINT learning_attempts_gq_path_accuracy_range CHECK (((gq_path_accuracy_pct IS NULL) OR ((gq_path_accuracy_pct >= (0)::numeric) AND (gq_path_accuracy_pct <= (100)::numeric))));
ALTER TABLE public.learning_attempts ADD CONSTRAINT learning_attempts_gq_path_efficiency_range CHECK (((gq_path_efficiency IS NULL) OR ((gq_path_efficiency >= (0)::numeric) AND (gq_path_efficiency <= (1)::numeric))));
ALTER TABLE public.learning_attempts ADD CONSTRAINT learning_attempts_no_unknown_key CHECK ((item_key <> ALL (ARRAY['unknown_word'::text, 'unknown'::text, 'null'::text, 'undefined'::text, ''::text])));
ALTER TABLE public.learning_attempts ADD CONSTRAINT learning_attempts_pkey PRIMARY KEY (id);
ALTER TABLE public.lios_adaptive_decisions ADD CONSTRAINT lios_adaptive_decisions_pkey PRIMARY KEY (id);
ALTER TABLE public.lios_adaptive_decisions ADD CONSTRAINT lios_adaptive_recovery_step_check CHECK (((recovery_step IS NULL) OR ((recovery_step >= 1) AND (recovery_step <= 5))));
ALTER TABLE public.lios_adaptive_decisions ADD CONSTRAINT lios_adaptive_regime_check CHECK ((regime = ANY (ARRAY['fresh'::text, 'flow'::text, 'productive'::text, 'boredom'::text, 'frustration'::text])));
ALTER TABLE public.lios_adaptive_decisions ADD CONSTRAINT lios_adaptive_reward_check CHECK ((reward_intensity = ANY (ARRAY['quiet'::text, 'standard'::text, 'big'::text])));
ALTER TABLE public.lios_adaptive_decisions ADD CONSTRAINT lios_adaptive_scaffold_check CHECK ((scaffold_level = ANY (ARRAY['none'::text, 'partial'::text, 'full'::text])));
ALTER TABLE public.lios_anomaly_fact ADD CONSTRAINT lios_anomaly_fact_pkey PRIMARY KEY (id);
ALTER TABLE public.lios_anomaly_fact ADD CONSTRAINT lios_anomaly_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'warn'::text, 'critical'::text])));
ALTER TABLE public.lios_pipeline_runs ADD CONSTRAINT lios_pipeline_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.mastery_episode_fact ADD CONSTRAINT mastery_episode_fact_pkey PRIMARY KEY (id);
ALTER TABLE public.mastery_episode_fact ADD CONSTRAINT mastery_episode_from_state_check CHECK (((from_state IS NULL) OR (from_state = ANY (ARRAY['Exposed'::text, 'Acquired'::text, 'Mastered'::text, 'Decayed'::text]))));
ALTER TABLE public.mastery_episode_fact ADD CONSTRAINT mastery_episode_to_state_check CHECK ((to_state = ANY (ARRAY['Exposed'::text, 'Acquired'::text, 'Mastered'::text, 'Decayed'::text])));
ALTER TABLE public.newsletter_subscribers ADD CONSTRAINT newsletter_subscribers_email_key UNIQUE (email);
ALTER TABLE public.newsletter_subscribers ADD CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id);
ALTER TABLE public.parent_controls ADD CONSTRAINT parent_controls_pkey PRIMARY KEY (child_profile_id);
ALTER TABLE public.parent_profiles ADD CONSTRAINT parent_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.parent_profiles ADD CONSTRAINT parent_profiles_stripe_customer_id_key UNIQUE (stripe_customer_id);
ALTER TABLE public.parent_subscriptions ADD CONSTRAINT parent_subscriptions_parent_id_key UNIQUE (parent_id);
ALTER TABLE public.parent_subscriptions ADD CONSTRAINT parent_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.parent_subscriptions ADD CONSTRAINT parent_subscriptions_stripe_subscription_id_key UNIQUE (stripe_subscription_id);
ALTER TABLE public.platform_admins ADD CONSTRAINT platform_admins_pkey PRIMARY KEY (user_id);
ALTER TABLE public.platform_insights ADD CONSTRAINT platform_insights_pkey PRIMARY KEY (id);
ALTER TABLE public.platform_insights ADD CONSTRAINT platform_insights_scope_check CHECK ((scope = ANY (ARRAY['platform'::text, 'activity'::text, 'growth'::text, 'operations'::text])));
ALTER TABLE public.platform_insights ADD CONSTRAINT platform_insights_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'suggestion'::text, 'warning'::text])));
ALTER TABLE public.playlists ADD CONSTRAINT playlists_difficulty_check CHECK ((difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])));
ALTER TABLE public.playlists ADD CONSTRAINT playlists_pkey PRIMARY KEY (id);
ALTER TABLE public.pricing_config ADD CONSTRAINT pricing_config_pkey PRIMARY KEY (id);
ALTER TABLE public.round_scores ADD CONSTRAINT round_scores_pkey PRIMARY KEY (id);
ALTER TABLE public.round_scores ADD CONSTRAINT round_scores_session_id_student_id_round_key UNIQUE (session_id, student_id, round);
ALTER TABLE public.round_scores ADD CONSTRAINT round_scores_stars_check CHECK (((stars >= 1) AND (stars <= 5)));
ALTER TABLE public.school_invites ADD CONSTRAINT school_invites_pkey PRIMARY KEY (id);
ALTER TABLE public.school_invites ADD CONSTRAINT school_invites_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])));
ALTER TABLE public.school_invites ADD CONSTRAINT school_invites_token_key UNIQUE (token);
ALTER TABLE public.school_teachers ADD CONSTRAINT school_teachers_pkey PRIMARY KEY (id);
ALTER TABLE public.school_teachers ADD CONSTRAINT school_teachers_role_check CHECK ((role = ANY (ARRAY['teacher'::text, 'school_admin'::text])));
ALTER TABLE public.school_teachers ADD CONSTRAINT school_teachers_school_id_teacher_id_key UNIQUE (school_id, teacher_id);
ALTER TABLE public.school_teachers ADD CONSTRAINT school_teachers_status_check CHECK ((status = ANY (ARRAY['invited'::text, 'active'::text, 'removed'::text])));
ALTER TABLE public.schools ADD CONSTRAINT schools_license_status_check CHECK ((license_status = ANY (ARRAY['active'::text, 'past_due'::text, 'cancelled'::text, 'grace_period'::text])));
ALTER TABLE public.schools ADD CONSTRAINT schools_license_tier_check CHECK ((license_tier = ANY (ARRAY['starter_5'::text, 'standard_10'::text, 'premium_25'::text, 'unlimited'::text])));
ALTER TABLE public.schools ADD CONSTRAINT schools_pkey PRIMARY KEY (id);
ALTER TABLE public.schools ADD CONSTRAINT schools_subscription_tier_check CHECK ((subscription_tier = ANY (ARRAY['free'::text, 'pro'::text])));
ALTER TABLE public.security_audit_log ADD CONSTRAINT security_audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.session_activities ADD CONSTRAINT session_activities_pkey PRIMARY KEY (id);
ALTER TABLE public.session_activities ADD CONSTRAINT session_activities_session_id_ordinal_key UNIQUE (session_id, ordinal);
ALTER TABLE public.session_activities ADD CONSTRAINT session_activities_state_check CHECK ((state = ANY (ARRAY['starting'::text, 'playing'::text, 'paused'::text, 'results'::text, 'ended'::text])));
ALTER TABLE public.session_network_fingerprints ADD CONSTRAINT session_network_fingerprints_pkey PRIMARY KEY (id);
ALTER TABLE public.session_network_fingerprints ADD CONSTRAINT session_network_fingerprints_session_id_key UNIQUE (session_id);
ALTER TABLE public.session_students ADD CONSTRAINT session_students_pkey PRIMARY KEY (id);
ALTER TABLE public.session_students ADD CONSTRAINT session_students_session_id_name_key UNIQUE (session_id, name);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_class_state_check CHECK ((class_state = ANY (ARRAY['lobby'::text, 'in_activity'::text, 'between_activities'::text, 'ended'::text])));
ALTER TABLE public.sessions ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_scoreboard_mode_check CHECK ((scoreboard_mode = ANY (ARRAY['full'::text, 'top3'::text, 'personal'::text, 'class'::text])));
ALTER TABLE public.sessions ADD CONSTRAINT sessions_status_check CHECK ((status = ANY (ARRAY['lobby'::text, 'playing'::text, 'paused'::text, 'results'::text, 'ended'::text])));
ALTER TABLE public.skill_state ADD CONSTRAINT skill_state_pkey PRIMARY KEY (device_id, item_key, game_mode);
ALTER TABLE public.skill_state_history ADD CONSTRAINT skill_state_history_pkey PRIMARY KEY (device_id, item_key, game_mode, day);
ALTER TABLE public.stripe_price_map ADD CONSTRAINT stripe_price_map_interval_check CHECK (("interval" = ANY (ARRAY['month'::text, 'year'::text])));
ALTER TABLE public.stripe_price_map ADD CONSTRAINT stripe_price_map_pkey PRIMARY KEY (price_key);
ALTER TABLE public.stripe_price_map ADD CONSTRAINT stripe_price_map_role_check CHECK ((role = ANY (ARRAY['base'::text, 'addon'::text])));
ALTER TABLE public.student_activity_assignments ADD CONSTRAINT student_activity_assignments_pkey PRIMARY KEY (id);
ALTER TABLE public.student_activity_assignments ADD CONSTRAINT student_activity_assignments_student_id_activity_key UNIQUE (student_id, activity);
ALTER TABLE public.teacher_insights ADD CONSTRAINT teacher_insights_insight_type_check CHECK ((insight_type = ANY (ARRAY['engagement'::text, 'activity'::text, 'timing'::text, 'recommendation'::text])));
ALTER TABLE public.teacher_insights ADD CONSTRAINT teacher_insights_pkey PRIMARY KEY (id);
ALTER TABLE public.teacher_insights ADD CONSTRAINT teacher_insights_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'suggestion'::text, 'warning'::text])));
ALTER TABLE public.teacher_insights ADD CONSTRAINT teacher_insights_source_check CHECK ((source = ANY (ARRAY['ai'::text, 'rule_engine'::text])));
ALTER TABLE public.teacher_profiles ADD CONSTRAINT teacher_profiles_auth_user_id_key UNIQUE (auth_user_id);
ALTER TABLE public.teacher_profiles ADD CONSTRAINT teacher_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.teachers ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);
ALTER TABLE public.teachers ADD CONSTRAINT teachers_tier_check CHECK ((tier = ANY (ARRAY['free'::text, 'trial'::text, 'pro'::text, 'school'::text, 'admin'::text])));
ALTER TABLE public.tenant_members ADD CONSTRAINT tenant_members_member_role_chk CHECK ((member_role = ANY (ARRAY['owner'::text, 'school_admin'::text, 'member'::text])));
ALTER TABLE public.tenant_members ADD CONSTRAINT tenant_members_pkey PRIMARY KEY (tenant_id, user_id);
ALTER TABLE public.tenants ADD CONSTRAINT tenants_kind_check CHECK ((kind = ANY (ARRAY['parent'::text, 'teacher'::text, 'school'::text, 'platform'::text])));
ALTER TABLE public.tenants ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);

-- ── Foreign keys (apply after all tables + PK/UNIQUE exist) ──────────
ALTER TABLE public.admin_alerts ADD CONSTRAINT admin_alerts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.analytics_events ADD CONSTRAINT analytics_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.billing_events ADD CONSTRAINT billing_events_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES parent_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.billing_events ADD CONSTRAINT billing_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.child_activity_summary ADD CONSTRAINT child_activity_summary_child_profile_id_fkey FOREIGN KEY (child_profile_id) REFERENCES child_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.child_activity_summary ADD CONSTRAINT child_activity_summary_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.child_learning_state ADD CONSTRAINT child_learning_state_child_profile_id_fkey FOREIGN KEY (child_profile_id) REFERENCES child_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.child_learning_state ADD CONSTRAINT child_learning_state_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.child_profiles ADD CONSTRAINT child_profiles_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES parent_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.child_profiles ADD CONSTRAINT child_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.class_children ADD CONSTRAINT class_children_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.classroom_default_activities ADD CONSTRAINT classroom_default_activities_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.client_errors ADD CONSTRAINT client_errors_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL;
ALTER TABLE public.client_errors ADD CONSTRAINT client_errors_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.consent_records ADD CONSTRAINT consent_records_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES parent_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.consent_records ADD CONSTRAINT consent_records_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.data_deletion_requests ADD CONSTRAINT data_deletion_requests_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES parent_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.data_deletion_requests ADD CONSTRAINT data_deletion_requests_target_child_id_fkey FOREIGN KEY (target_child_id) REFERENCES child_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.data_deletion_requests ADD CONSTRAINT data_deletion_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.form_submissions ADD CONSTRAINT form_submissions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.human_observation_fact ADD CONSTRAINT human_observation_fact_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.item_difficulty ADD CONSTRAINT item_difficulty_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.learning_attempts ADD CONSTRAINT learning_attempts_child_profile_id_fkey FOREIGN KEY (child_profile_id) REFERENCES child_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.learning_attempts ADD CONSTRAINT learning_attempts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.lios_adaptive_decisions ADD CONSTRAINT lios_adaptive_decisions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.lios_anomaly_fact ADD CONSTRAINT lios_anomaly_fact_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.lios_pipeline_runs ADD CONSTRAINT lios_pipeline_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.mastery_episode_fact ADD CONSTRAINT mastery_episode_fact_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.newsletter_subscribers ADD CONSTRAINT newsletter_subscribers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.parent_controls ADD CONSTRAINT parent_controls_child_profile_id_fkey FOREIGN KEY (child_profile_id) REFERENCES child_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.parent_controls ADD CONSTRAINT parent_controls_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES parent_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.parent_controls ADD CONSTRAINT parent_controls_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.parent_profiles ADD CONSTRAINT parent_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.parent_profiles ADD CONSTRAINT parent_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.parent_subscriptions ADD CONSTRAINT parent_subscriptions_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES parent_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.parent_subscriptions ADD CONSTRAINT parent_subscriptions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.platform_admins ADD CONSTRAINT platform_admins_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.platform_admins ADD CONSTRAINT platform_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.platform_insights ADD CONSTRAINT platform_insights_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.playlists ADD CONSTRAINT playlists_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id);
ALTER TABLE public.playlists ADD CONSTRAINT playlists_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.playlists ADD CONSTRAINT playlists_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.pricing_config ADD CONSTRAINT pricing_config_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.round_scores ADD CONSTRAINT round_scores_session_activity_id_fkey FOREIGN KEY (session_activity_id) REFERENCES session_activities(id) ON DELETE CASCADE;
ALTER TABLE public.round_scores ADD CONSTRAINT round_scores_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.round_scores ADD CONSTRAINT round_scores_student_id_fkey FOREIGN KEY (student_id) REFERENCES session_students(id) ON DELETE CASCADE;
ALTER TABLE public.round_scores ADD CONSTRAINT round_scores_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.school_invites ADD CONSTRAINT school_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id);
ALTER TABLE public.school_invites ADD CONSTRAINT school_invites_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.school_invites ADD CONSTRAINT school_invites_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.school_teachers ADD CONSTRAINT school_teachers_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id);
ALTER TABLE public.school_teachers ADD CONSTRAINT school_teachers_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.school_teachers ADD CONSTRAINT school_teachers_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id);
ALTER TABLE public.school_teachers ADD CONSTRAINT school_teachers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.schools ADD CONSTRAINT schools_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES auth.users(id);
ALTER TABLE public.schools ADD CONSTRAINT schools_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.security_audit_log ADD CONSTRAINT security_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.session_activities ADD CONSTRAINT session_activities_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.session_activities ADD CONSTRAINT session_activities_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.session_network_fingerprints ADD CONSTRAINT session_network_fingerprints_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.session_students ADD CONSTRAINT session_students_class_child_id_fkey FOREIGN KEY (class_child_id) REFERENCES class_children(id) ON DELETE SET NULL;
ALTER TABLE public.session_students ADD CONSTRAINT session_students_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.session_students ADD CONSTRAINT session_students_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_current_activity_id_fkey FOREIGN KEY (current_activity_id) REFERENCES session_activities(id) ON DELETE SET NULL;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_playlist_id_fkey FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE SET NULL;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE CASCADE;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.skill_state ADD CONSTRAINT skill_state_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.skill_state_history ADD CONSTRAINT skill_state_history_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.stripe_price_map ADD CONSTRAINT stripe_price_map_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.student_activity_assignments ADD CONSTRAINT student_activity_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id);
ALTER TABLE public.student_activity_assignments ADD CONSTRAINT student_activity_assignments_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.student_activity_assignments ADD CONSTRAINT student_activity_assignments_student_id_fkey FOREIGN KEY (student_id) REFERENCES session_students(id) ON DELETE CASCADE;
ALTER TABLE public.teacher_insights ADD CONSTRAINT teacher_insights_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.teacher_insights ADD CONSTRAINT teacher_insights_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.teacher_profiles ADD CONSTRAINT teacher_profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.teacher_profiles ADD CONSTRAINT teacher_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.teachers ADD CONSTRAINT teachers_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.teachers ADD CONSTRAINT teachers_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;
ALTER TABLE public.teachers ADD CONSTRAINT teachers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE public.tenant_members ADD CONSTRAINT tenant_members_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.tenant_members ADD CONSTRAINT tenant_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;

-- ── Secondary indexes (constraint-backed indexes are created above) ──
CREATE INDEX analytics_events_attempt_idx ON public.analytics_events USING btree (attempt_id, occurred_at) WHERE (attempt_id IS NOT NULL);
CREATE INDEX analytics_events_device_idx ON public.analytics_events USING btree (device_id, occurred_at DESC) WHERE (device_id IS NOT NULL);
CREATE UNIQUE INDEX analytics_events_event_uid_uidx ON public.analytics_events USING btree (event_uid);
CREATE INDEX analytics_events_mode_idx ON public.analytics_events USING btree (game_mode, occurred_at DESC) WHERE (game_mode IS NOT NULL);
CREATE INDEX analytics_events_name_idx ON public.analytics_events USING btree (event_name, occurred_at DESC);
CREATE INDEX analytics_events_occurred_at_idx ON public.analytics_events USING btree (occurred_at DESC);
CREATE INDEX analytics_events_real_prod_idx ON public.analytics_events USING btree (occurred_at DESC) WHERE ((traffic_type = 'real'::text) AND (environment = 'production'::text));
CREATE INDEX analytics_events_session_idx ON public.analytics_events USING btree (session_id, occurred_at);
CREATE INDEX class_children_teacher_idx ON public.class_children USING btree (teacher_id) WHERE (archived = false);
CREATE INDEX data_deletion_requests_target_child_id_idx ON public.data_deletion_requests USING btree (target_child_id);
CREATE INDEX human_observation_recorded_idx ON public.human_observation_fact USING btree (recorded_at DESC);
CREATE INDEX idx_activity_summary_child ON public.child_activity_summary USING btree (child_profile_id);
CREATE INDEX idx_attempts_child ON public.learning_attempts USING btree (child_profile_id);
CREATE INDEX idx_billing_events_parent ON public.billing_events USING btree (parent_id);
CREATE INDEX idx_child_profiles_parent ON public.child_profiles USING btree (parent_id);
CREATE INDEX idx_child_profiles_status ON public.child_profiles USING btree (parent_id, status);
CREATE INDEX idx_child_profiles_tenant ON public.child_profiles USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX idx_client_errors_reported ON public.client_errors USING btree (reported_at DESC);
CREATE INDEX idx_client_errors_session_id ON public.client_errors USING btree (session_id);
CREATE INDEX idx_consent_parent ON public.consent_records USING btree (parent_id);
CREATE INDEX idx_deletion_parent ON public.data_deletion_requests USING btree (parent_id);
CREATE INDEX idx_form_submissions_created ON public.form_submissions USING btree (created_at DESC);
CREATE INDEX idx_learning_attempts_tenant ON public.learning_attempts USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX idx_network_fingerprints_hash ON public.session_network_fingerprints USING btree (network_hash);
CREATE INDEX idx_network_fingerprints_session ON public.session_network_fingerprints USING btree (session_id);
CREATE INDEX idx_parent_controls_parent ON public.parent_controls USING btree (parent_id);
CREATE INDEX idx_parent_subscriptions_customer ON public.parent_subscriptions USING btree (stripe_customer_id);
CREATE INDEX idx_parent_subscriptions_parent ON public.parent_subscriptions USING btree (parent_id);
CREATE INDEX idx_playlists_school_id ON public.playlists USING btree (school_id);
CREATE INDEX idx_playlists_teacher ON public.playlists USING btree (teacher_id);
CREATE INDEX idx_round_scores_activity ON public.round_scores USING btree (activity);
CREATE INDEX idx_round_scores_session_id ON public.round_scores USING btree (session_id);
CREATE UNIQUE INDEX idx_round_scores_unique_submission ON public.round_scores USING btree (session_id, student_id, round_number) WHERE (student_id IS NOT NULL);
CREATE INDEX idx_school_invites_invited_by ON public.school_invites USING btree (invited_by);
CREATE INDEX idx_school_invites_school_id ON public.school_invites USING btree (school_id);
CREATE INDEX idx_school_teachers_invited_by ON public.school_teachers USING btree (invited_by);
CREATE INDEX idx_school_teachers_school ON public.school_teachers USING btree (school_id);
CREATE INDEX idx_school_teachers_teacher ON public.school_teachers USING btree (teacher_id);
CREATE INDEX idx_schools_admin ON public.schools USING btree (admin_user_id);
CREATE INDEX idx_sec_audit_created ON public.security_audit_log USING btree (created_at DESC);
CREATE INDEX idx_sec_audit_type ON public.security_audit_log USING btree (event_type, created_at DESC);
CREATE INDEX idx_sec_audit_user ON public.security_audit_log USING btree (user_id, created_at DESC);
CREATE INDEX idx_session_students_tenant ON public.session_students USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX idx_sessions_school_id ON public.sessions USING btree (school_id);
CREATE INDEX idx_sessions_teacher_id ON public.sessions USING btree (teacher_id);
CREATE INDEX idx_sessions_teacher_status ON public.sessions USING btree (teacher_id, status);
CREATE INDEX idx_sessions_tenant ON public.sessions USING btree (tenant_id) WHERE (tenant_id IS NOT NULL);
CREATE INDEX idx_student_assignments_session_activity ON public.student_activity_assignments USING btree (session_id, activity);
CREATE INDEX idx_student_assignments_session_student_seq ON public.student_activity_assignments USING btree (session_id, student_id, sequence_order);
CREATE INDEX idx_student_assignments_student ON public.student_activity_assignments USING btree (student_id);
CREATE INDEX idx_teacher_insights_expires ON public.teacher_insights USING btree (expires_at);
CREATE INDEX idx_teacher_insights_teacher ON public.teacher_insights USING btree (teacher_id);
CREATE INDEX idx_teachers_school_id ON public.teachers USING btree (school_id);
CREATE INDEX learning_attempts_device_item_idx ON public.learning_attempts USING btree (device_id, item_key, occurred_at DESC);
CREATE INDEX learning_attempts_elo_pending_idx ON public.learning_attempts USING btree (occurred_at) WHERE ((elo_processed_at IS NULL) AND (credibility_score IS NOT NULL));
CREATE UNIQUE INDEX learning_attempts_event_uid_uidx ON public.learning_attempts USING btree (event_uid);
CREATE INDEX learning_attempts_mode_idx ON public.learning_attempts USING btree (game_mode, occurred_at DESC);
CREATE INDEX learning_attempts_session_idx ON public.learning_attempts USING btree (session_id, occurred_at);
CREATE INDEX learning_attempts_tier_idx ON public.learning_attempts USING btree (credibility_tier, occurred_at DESC) WHERE (credibility_tier IS NOT NULL);
CREATE INDEX learning_attempts_unscored_idx ON public.learning_attempts USING btree (occurred_at DESC) WHERE (credibility_score IS NULL);
CREATE INDEX lios_adaptive_decisions_device_idx ON public.lios_adaptive_decisions USING btree (device_id, made_at DESC);
CREATE INDEX lios_adaptive_decisions_made_idx ON public.lios_adaptive_decisions USING btree (made_at DESC);
CREATE INDEX lios_anomaly_detected_idx ON public.lios_anomaly_fact USING btree (detected_at DESC);
CREATE INDEX lios_anomaly_metric_idx ON public.lios_anomaly_fact USING btree (metric, detected_at DESC);
CREATE INDEX lios_pipeline_runs_time_idx ON public.lios_pipeline_runs USING btree (run_at DESC);
CREATE INDEX mastery_episode_learner_idx ON public.mastery_episode_fact USING btree (device_id, item_key, game_mode, transition_at DESC);
CREATE INDEX mastery_episode_state_idx ON public.mastery_episode_fact USING btree (to_state, transition_at DESC);
CREATE INDEX mastery_episode_time_idx ON public.mastery_episode_fact USING btree (transition_at DESC);
CREATE INDEX round_scores_activity_idx ON public.round_scores USING btree (session_activity_id);
CREATE INDEX round_scores_session_idx ON public.round_scores USING btree (session_id, round);
CREATE INDEX round_scores_student_idx ON public.round_scores USING btree (student_id);
CREATE INDEX session_activities_session_idx ON public.session_activities USING btree (session_id, started_at DESC);
CREATE INDEX session_students_active_idx ON public.session_students USING btree (session_id) WHERE (kicked_at IS NULL);
CREATE INDEX session_students_class_child_idx ON public.session_students USING btree (class_child_id) WHERE (class_child_id IS NOT NULL);
CREATE INDEX session_students_session_idx ON public.session_students USING btree (session_id);
CREATE UNIQUE INDEX sessions_active_code_idx ON public.sessions USING btree (code) WHERE (status <> 'ended'::text);
CREATE INDEX sessions_current_activity_id_idx ON public.sessions USING btree (current_activity_id);
CREATE INDEX sessions_playlist_id_idx ON public.sessions USING btree (playlist_id);
CREATE INDEX sessions_teacher_idx ON public.sessions USING btree (teacher_id, created_at DESC);
CREATE INDEX skill_state_device_idx ON public.skill_state USING btree (device_id, last_attempt_at DESC);
CREATE INDEX skill_state_item_idx ON public.skill_state USING btree (item_key, game_mode, theta DESC);
