-- WP1A.2 staging sync 04: function EXECUTE grants aligned to production proacl (aclexplode) 2026-09-08; plus 5 table ACLs.
DO $$
DECLARE sig text; roles text; grp record;
BEGIN
  FOR grp IN SELECT * FROM (VALUES
    ('anon, authenticated, service_role', ARRAY[
      'public.ingest_analytics_events(in_events jsonb)',
      'public.ingest_learning_attempts(in_attempts jsonb)']),
    ('authenticated, service_role', ARRAY[
      'public.lios_detect_mastery_episodes_v1()',
      'public._class_assert_teacher(in_session_id uuid)',
      'public._get_child_skills(p_child uuid)',
      'public._is_admin()',
      'public._stamp_child_tenant()',
      'public._stamp_parent_profile_tenant()',
      'public._stamp_parent_tenant()',
      'public._stamp_session_tenant()',
      'public._stamp_teacher_tenant()',
      'public.archive_child_profile(p_child uuid)',
      'public.auth_owns_child(child uuid)',
      'public.bump_child_activity_summary()',
      'public.bump_child_learning_state()',
      'public.check_join_rate_limit(in_ip_hash text)',
      'public.class_delete_session(in_session_id uuid)',
      'public.class_end_activity(in_session_id uuid)',
      'public.class_end_session(in_session_id uuid)',
      'public.class_end_stale_sessions()',
      'public.class_join_with_network(in_session_id uuid, in_name text, in_network_fingerprint text)',
      'public.class_kick_student(in_session_id uuid, in_student_id uuid, in_reason text)',
      'public.class_pause_activity(in_session_id uuid)',
      'public.class_resume_activity(in_session_id uuid)',
      'public.class_set_scoreboard_visibility(in_session_id uuid, in_visible boolean)',
      'public.class_start_activity(in_session_id uuid, in_activity text)',
      'public.class_student_stats(in_session_id uuid, in_student_id uuid)',
      'public.class_summary(in_session_id uuid)',
      'public.create_child_profile(p_nickname text, p_age_band text, p_learning_focus text, p_avatar text, p_preferred_hand text, p_consent_version text)',
      'public.dashboard_ab_results(in_flag text)',
      'public.dashboard_adaptive_decisions(in_days integer)',
      'public.dashboard_anomaly_check()',
      'public.dashboard_classrooms(in_days integer)',
      'public.dashboard_cohort_curves(in_weeks integer)',
      'public.dashboard_cohort_retention(in_weeks integer)',
      'public.dashboard_context_split(in_days integer)',
      'public.dashboard_curriculum_coverage(in_days integer)',
      'public.dashboard_daily_digest()',
      'public.dashboard_engagement_deep(in_days integer)',
      'public.dashboard_errors(row_limit integer)',
      'public.dashboard_executive_summary(in_days integer)',
      'public.dashboard_export_headline(in_days integer)',
      'public.dashboard_friction_engineering(in_days integer)',
      'public.dashboard_funnel(in_days integer)',
      'public.dashboard_gesture_quality(in_days integer)',
      'public.dashboard_ingest_latency(in_days integer)',
      'public.dashboard_latest_sessions(row_limit integer)',
      'public.dashboard_live()',
      'public.dashboard_mastery(in_days integer, in_min_attempts integer)',
      'public.dashboard_mastery_milestones(in_days integer, in_min_attempts integer, in_threshold_pct integer)',
      'public.dashboard_mastery_summary(in_days integer)',
      'public.dashboard_mastery_v2(in_days integer)',
      'public.dashboard_observability(in_days integer)',
      'public.dashboard_observations(in_days integer)',
      'public.dashboard_pipeline_status(in_limit integer)',
      'public.dashboard_progression_for_learner(in_device_id text)',
      'public.dashboard_progression_top_learners(in_days integer, in_limit integer)',
      'public.dashboard_retention_deep()',
      'public.dashboard_today()',
      'public.dashboard_top_modes(in_days integer)',
      'public.dashboard_tracker_health(in_days integer)',
      'public.dashboard_trust_strip(in_days integer)',
      'public.export_family_data()',
      'public.export_parent_data()',
      'public.get_account_roles()',
      'public.get_child_dashboard(p_child uuid)',
      'public.get_effective_tier(teacher_id uuid)',
      'public.get_parent_overview()',
      'public.get_weekly_summary(p_child uuid)',
      'public.handle_new_parent_user()',
      'public.handle_new_teacher_user()',
      'public.handle_new_user()',
      'public.has_parent_role()',
      'public.has_teacher_role()',
      'public.initialize_teacher_trial()',
      'public.is_platform_admin()',
      'public.is_school_admin(in_tenant uuid)',
      'public.lios_detect_anomalies_v1()',
      'public.lios_detect_friction_v1(p_lookback interval)',
      'public.lios_detect_mastery_episodes_v1(p_lookback interval)',
      'public.lios_recommend_next(p_device_id text, p_session_id uuid, p_game_mode text, p_current_item text, p_was_correct boolean)',
      'public.lios_record_observation(p_device_id text, p_focus_tags text[], p_affect_tags text[], p_independence_tags text[], p_social_tags text[], p_notable_tags text[], p_session_id uuid, p_classroom_code text, p_age_band text, p_note text, p_observer_role text)',
      'public.lios_run_pipeline(p_lookback interval)',
      'public.lios_score_unscored_attempts(p_lookback interval)',
      'public.lios_update_elo_v1(p_lookback interval)',
      'public.log_security_event(in_event_type text, in_metadata jsonb, in_ip_hash text, in_ua_hash text, in_country text)',
      'public.parent_has_access(p_parent uuid)',
      'public.parent_subscription_state(p_parent uuid)',
      'public.record_consent(p_consent_type text, p_consent_version text, p_granted boolean)',
      'public.register_parent()',
      'public.register_teacher(in_full_name text, in_school_name text)',
      'public.request_account_deletion()',
      'public.request_child_deletion(p_child uuid)',
      'public.restore_child_profile(p_child uuid)',
      'public.session_set_network_fingerprint(in_session_id uuid, in_teacher_ip text)',
      'public.session_validate_network(in_session_id uuid, in_network_fingerprint text)',
      'public.set_classroom_default_activities(in_session_id uuid, in_activities text[])',
      'public.set_session_school_id()',
      'public.set_student_assignments(in_session_id uuid, in_student_id uuid, in_activities jsonb)',
      'public.sync_teacher_school_tier()',
      'public.user_tenant_ids()']),
    ('PUBLIC, anon, authenticated, service_role', ARRAY[
      'public.lios_is_technical_item_key(k text)']),
    ('service_role', ARRAY[
      'public._ensure_tenant(in_kind text, in_owner uuid, in_name text)',
      'public.get_email_cron_key()',
      'public.process_account_deletion_requests(p_limit integer)',
      'public.start_parent_trial(p_parent uuid)']),
    ('authenticated, service_role, anon', ARRAY[
      'public.class_validate_join(in_code text, in_network_fingerprint text)',
      'public.get_student_assignments(in_student_id uuid, in_session_id uuid)',
      'public.is_admin_user(check_user_id uuid)',
      'public.session_lookup_by_code(in_code text)'])
  ) v(roles, sigs) LOOP
    FOREACH sig IN ARRAY grp.sigs LOOP
      EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated, service_role', sig);
      EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO %s', sig, grp.roles);
    END LOOP;
  END LOOP;
END $$;

-- table ACLs (prod has revoked anon/authenticated on these)
REVOKE ALL ON TABLE public.join_audit_log FROM anon;
REVOKE ALL ON TABLE public.join_rate_limits FROM anon, authenticated;
REVOKE ALL ON TABLE public.platform_admins FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.security_audit_log FROM anon, authenticated;
REVOKE ALL ON TABLE public.session_network_fingerprints FROM anon, authenticated;
